/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oferovadia.songslyrics;

import java.io.*;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showConfirmDialog;
/**
 *
 * @author ofero
 */
public class SongsLyrics extends javax.swing.JFrame {

    /**
     * Creates new form SongsLyrics
     */
    public SongsLyrics() {
        initComponents();
        try {
            FileWriter writer = new FileWriter(".code.py");
            writer.write(code);
            writer.close();
        }
        catch (IOException e){
            showMessageDialog(null, "Error Writing code to file! (error number - 1, description: error or failure while writing to a file named \".code.py\"");
        }
        try{
            Process test =  Runtime.getRuntime().exec("python .code.py");
        }
        catch (IOException e){
            showMessageDialog(null, "Make sure you have python 3.7 or above installer properly on your computer");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 20));
        jLabel1.setText("Enter artist name: ");

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 20));
        jLabel2.setText("Enter song name: ");

        jTextField1.setFont(new java.awt.Font("Roboto Light", 0, 18));
        jTextField1.setToolTipText("");

        jTextField2.setFont(new java.awt.Font("Roboto Light", 0, 18));
        jTextField2.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto Light", 0, 16));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 20));
        jButton1.setText("Get Lyrics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                    showMessageDialog(null, "Error!");
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2))
                                                .addGap(523, 523, 523))))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        String artist = jTextField1.getText();
        String song = jTextField2.getText();
        try{
            //Process p = Runtime.getRuntime().exec("python D:\\OFER\\Java\\projects\\SongsLyrics\\src\\getLyrics.py " + "\"" + artist + "\"" + " " + "\"" + song + "\"");
            Process p = Runtime.getRuntime().exec("python .code.py " + "\"" + artist + "\"" + " " + "\"" + song + "\"");
            BufferedReader stdIn = new BufferedReader(new
                    InputStreamReader(p.getInputStream()));

            String lyric = stdIn.readLine();
        }
        catch(IOException e){
            showMessageDialog(null, "Error! cannot excute external script!");
            return;
        }
        //Process pro = Runtime.getRuntime().exec("python D:\\OFER\\Java\\projects\\SongsLyrics\\src\\getLyrics.py " + "\"" + artist + "\"" + " " + "\"" + song + "\"");
        jTextArea1.setText("");
        Process pro = Runtime.getRuntime().exec("python .code.py " + "\"" + artist + "\"" + " " + "\"" + song + "\"");
        //jTextArea1.setText(p);
        //System.out.println(pro);
        //String lyrics = String.valueOf(pro.toString());
        BufferedReader stdInput = new BufferedReader(new
                InputStreamReader(pro.getInputStream()));
        // buffer for storing file contents in memory
        StringBuffer stringBuffer = new StringBuffer("");
// for reading one line
        String line = null;
// keep reading till readLine returns null
        while ((line = stdInput.readLine()) != null) {
            // keep appending last line read to buffer
            stringBuffer.append(line);
            //System.out.println(line);
            jTextArea1.setText(jTextArea1.getText() + line+ "\n");
        }
        //String lyrics = stringBuffer.toString();
        //jTextArea1.setText(lyrics);
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
        File file = new File(".code.py");        // TODO add your handling code here:
        if(file.delete()){
            return;
        }
        else{
            showMessageDialog(null, "Error while deleting \".code.py\" file (error code - 2)");
        }
    }
    private void formWindowClosed(java.awt.event.WindowEvent evt) {
        /*
        File file = new File(".code.py");        // TODO add your handling code here:
        if(file.delete()){
            return;
        }
        else{
            showMessageDialog(null, "Error while deleting \".code.py\" file (error code - 2)");
        }        // TODO add your handling code here:

         */
        return;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SongsLyrics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SongsLyrics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SongsLyrics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SongsLyrics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SongsLyrics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration
    public String code = "try:\n" +
            "	import lyricwikia \n" +
            "except ModuleNotFoundError:\n" +
            "	import os\n" +
            "	os.system(\"pip install lyricwikia\")\n" +
            "	import lyricwikia\n" +
            "\n" +
            "class getLyrics():\n" +
            "	def __init__(self, artist, song):\n" +
            "		self.artist = artist\n" +
            "		self.song = song\n" +
            "	def get_lyrics(self):\n" +
            "		try:\n" +
            "			lyrics = lyricwikia.get_lyrics(self.artist, self.song)\n" +
            "		except Exception:\n" +
            "			print(\"Error!\")\n" +
            "			return\n" +
            "		print(lyrics)\n" +
            "if __name__ == '__main__':\n" +
            "	import sys\n" +
            "	args = sys.argv\n" +
            "	lyrics = getLyrics(args[1], args[2])\n" +
            "	lyrics.get_lyrics()\n" +
            "	\n" +
            "		";
}
